version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-motivator-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jjzbu48izjp1"
s3_prefix = "lambda-motivator-app"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
